============================= test session starts ==============================
platform darwin -- Python 3.9.6, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/1cebearpooh/Documents/homework/sysSecurity/final_project/DynaPyt
configfile: pyproject.toml
plugins: anyio-4.6.2.post1, xdist-3.6.1
created: 8/8 workers
8 workers [0 items]


=============================== warnings summary ===============================
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
  /Users/1cebearpooh/Documents/homework/sysSecurity/final_project/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
../.venv/lib/python3.9/site-packages/urllib3/__init__.py:35
======================== 8 warnings in 0.65s =========================
